### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by jemunm378** [RedGuy12/scratchdit#2]
A bunch of error messages are on the home page. It looks like it’s due to the recent commit.

**Comment by RedGuy12** [comment]
ik, working on it now
________________________________

**Comment by RedGuy12** [comment]
```
2021-02-15T17:58:43.340324+00:00 app[web.1]: [15-Feb-2021 17:58:43 UTC] PHP Warning:  Trying to access array offset on value of type null in /app/inc/functions_task.php on line 101
```

**Comment by jemunm378** [comment]
@RedGuy12 Maybe use isset?

**Comment by RedGuy12** [comment]
maybe...but I'm trying to figure out why it is not set. instead of just removing the error, we should remove the cause.

**Comment by jemunm378** [comment]
Okay

**Comment by RedGuy12** [comment]
k, so the latest commit made it always show error details...now we have a ton more...

**Comment by jemunm378** [comment]
@RedGuy12 Yikes. Okay.

**Comment by RedGuy12** [comment]
well, at least the forum works now..even if there's no css...

**Comment by RedGuy12** [comment]
i am ending up just using `isset()` or `array_key_exists()` for most

it's fine bc most are just unset configurations that will be set eventually

**Comment by jemunm378** [comment]
Okay

**Comment by jemunm378** [comment]
@RedGuy12 I found out php version 8 is no supported. We need to utilize composer and create a composer.json to change the php version.

**Comment by jemunm378** [comment]
I think I fixed this issue. Now we just need to install myBB and I think we are good to go.

**Comment by jemunm378** [comment]
But there's another problem. I put the stack version on 16, which end of life will be in May. You should edit the composer.json file and make it require php with a version below 8.0.

**Comment by jemunm378** [comment]
@RedGuy12 I had put the heroku stack version to 16 because php 8 is not supported. Your deploy bump it back up to 20.

**Comment by RedGuy12** [comment]
ik, you can use php 7 without stack 16
________________________________

**Comment by jemunm378** [comment]
@RedGuy12 Doing this should delete all errors messages and get back the css.

**Comment by RedGuy12** [comment]
i got it
________________________________

**Comment by jemunm378** [comment]
Okay.

**Comment by jemunm378** [comment]
@Redguy12 You should try running the upgrade script after making changes to fix issue 42.

**Comment by RedGuy12** [comment]
> @RedGuy12 You should try running the upgrade script after making changes to fix issue 42.

what 


anyway, fixed
