### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by RedGuy12** [RedGuy12/scratchdit#3]
```
 !     WARNING: No 'composer.json' found!
 !     
 !     Your project only contains an 'index.php', no 'composer.json'.
 !     
 !     Using 'index.php' to declare app type as PHP is deprecated and
 !     may lead to unexpected behavior.
 !     
 !     Please consider updating your codebase to utilize Composer and
 !     modern dependency management in order to benefit from the latest
 !     PHP runtimes and improved application performance, as well as
 !     control over the PHP versions and extensions available.
 !     
 !     For an introduction to dependency management with Composer and
 !     how to get the most out of PHP on Heroku, refer to the docs at
 !     https://getcomposer.org/doc/00-intro.md and
 !     https://devcenter.heroku.com/articles/getting-started-with-php
```

i need to learn the structure of `composer.json`...but if someone else wants to do this, help is appreciated. we're on `Composer version 1.10.20 2021-01-27 15:41:06` if you need it
add a runtime to the composer file too
```
NOTICE: No runtime required in composer.lock; using PHP ^7.0.0 | ^8.0.0
- apache (2.4.46)
- nginx (1.18.0)
- php (8.0.2)
- composer (1.10.20)
```

**Comment by jemunm378** [comment]
Looks like composer is a Dependency Manager for PHP. I found a tutorial on how to make it work: (https://getcomposer.org/doc/00-intro.md#installation-windows). If your on Linux or Mac OS: (https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos).

**Comment by jemunm378** [comment]
You should install composer on your computer first.

**Comment by jemunm378** [comment]
@RedGuy12, I’m going to install composer on my computer and utilize it with heroku. But I might need to be an admin in heroku, I’m not sure.

**Comment by RedGuy12** [comment]
@jemunm378 I believe you are an admin now...did you get a confirmation email or something? if not, try accessing the dashboard again
________________________________

**Comment by jemunm378** [comment]
I think i fixed this issue. Closing.

**Comment by RedGuy12** [comment]
How did you fix it?
________________________________
